### ISSUE TITLE
Images for README.md

### ISSUE THREAD

**Issue by Rhym** [Rhym/silverstripe-cms-theme#1]
![demo-image](https://cloud.githubusercontent.com/assets/1136811/7264694/a272d25c-e8e2-11e4-8981-4216ad31f09e.png)

**Comment by stevie-mayhew** [comment]
![screen shot 2015-08-03 at 10 50 19 am](https://cloud.githubusercontent.com/assets/1953220/9028460/9f5b5238-39cd-11e5-8d49-e81f8e56cdbe.png)
![screen shot 2015-08-03 at 10 51 27 am](https://cloud.githubusercontent.com/assets/1953220/9028461/9f5b9824-39cd-11e5-8655-3016fe71120f.png)

**Comment by Rhym** [comment]
![default](https://cloud.githubusercontent.com/assets/1136811/9029315/c9cb7eea-39e5-11e5-8948-9acb16ce3df9.jpg)
![grouped-menu](https://cloud.githubusercontent.com/assets/1136811/9029316/c9cffcfe-39e5-11e5-86d8-47e5dbd7e962.jpg)

**Comment by Rhym** [comment]
![cms-grouped-menu](https://cloud.githubusercontent.com/assets/1136811/9187064/631d9a98-4020-11e5-9ca6-31b10c12fc2d.jpg)
![cms-menu](https://cloud.githubusercontent.com/assets/1136811/9187063/631bfa4e-4020-11e5-954b-8e787d229b1e.jpg)

**Comment by Rhym** [comment]
![cms-menu](https://cloud.githubusercontent.com/assets/1136811/9187098/c6951f74-4020-11e5-9367-9f7a9cb00ec2.jpg)

**Comment by Rhym** [comment]
![unicode](https://cloud.githubusercontent.com/assets/1136811/9187509/aab709de-4025-11e5-987e-aff1f6e67de2.jpg)

**Comment by Rhym** [comment]
![cms-grouped-menu](https://cloud.githubusercontent.com/assets/1136811/9187572/5b2ab504-4026-11e5-9d78-bb2f9fb04f74.jpg)
