### ISSUE TITLE
SilverShop compatibility?

### ISSUE THREAD

**Issue by camexapps** [Rhym/silverstripe-cms-theme#19]
Not sure if specific to the SilverShop module (https://packagist.org/packages/silvershop/core) or not,  but appears the side 'Filter' is hiding some content when  expanded/contracted:

![screen shot 2017-04-07 at 08 38 41](https://cloud.githubusercontent.com/assets/1858524/24774605/af3801b4-1b6d-11e7-9020-cf3259658045.png)
![screen shot 2017-04-07 at 08 38 35](https://cloud.githubusercontent.com/assets/1858524/24774607/b1793722-1b6d-11e7-946c-52dcc8e4352e.png)

**Comment by Rhym** [comment]
I've never used silvershop before. What does it do with the cms theme disabled?

**Comment by camexapps** [comment]
Thanks @Rhym Gonna close this, feel like a bit of a dummy, looks the the issue is at there end..

**Comment by Rhym** [comment]
No problem, man.
