### ISSUE TITLE
SubSites Module Support

### ISSUE THREAD

**Issue by camexapps** [Rhym/silverstripe-cms-theme#21]
Hey ya,

Just realised it needs a bit of TLC to work with the SubSites module (if this is something yoiu are willing to do of course!). After I had installed the SubSites module (https://github.com/silverstripe/silverstripe-subsites), this was the admin section:

Before SubSites Module: 
![screen shot 2017-09-11 at 13 31 14](https://user-images.githubusercontent.com/1858524/30255176-83292860-96f5-11e7-82b1-1ff28eb2d61d.png)

After SubSites Module Installed:

![screen shot 2017-09-11 at 13 27 16](https://user-images.githubusercontent.com/1858524/30255138-24075c12-96f5-11e7-933c-ff2c25716839.png)

Could be related issue?:

https://github.com/symbiote/silverstripe-grouped-cms-menu/issues/8

**Comment by Rhym** [comment]
Supported as of: 26cd4a7c12f87e01a20f0cb69978f566cb2fb47a
