### ISSUE TITLE
Repsonsive colors for hamburger

### ISSUE THREAD

**Issue by mrgray** [Rhym/silverstripe-cms-theme#24]
So everything works beautifully except it doesn't seem to modify the hamburger that's initialized on the responsive version; attaching a screenshot.

![screenshot-2018-2-25 silverstripe - pages](https://user-images.githubusercontent.com/785940/36640362-cf0a9f9a-1a42-11e8-8b5c-45888c54a74e.png)

**Comment by Rhym** [comment]
Ah, good catch. I feel for you having to work on a project in mobile.

097540e
