### ISSUE TITLE
Restrict the size of the logo

### ISSUE THREAD

**Issue by Firesphere** [Rhym/silverstripe-cms-theme#25]
Currently, when either uploading or setting a logo from config, the full size is displayed. An option to restrict it to a smaller size and use a resized image would give more flexibility to use high quality images for setting/uploading, without pushing down the menu too much.

**Comment by Rhym** [comment]
Can do. I think it used to do it, but there was an update form SS to the sidebar, and I must not have checked that bit. Will fix tomorrow.
