### ISSUE TITLE
Why is the menu not collapsible?

### ISSUE THREAD

**Issue by Firesphere** [Rhym/silverstripe-cms-theme#63]
I know it's popped up a few times, but it seems that the left menu can not be collapsed when this module is installed.

How come, and what would be a work-around? Or where to look for building a work-around? I'd like to be able to reinstate the collapsing again :) (Especially on smaller screens!)

**Comment by Rhym** [comment]
Initially, because I built this for myself, I just couldn't be arsed implementing it 😂

**Comment by Firesphere** [comment]
I guess I solved the problem myself 😆
