### ISSUE TITLE
Silverstripe 3.2 compatibility

### ISSUE THREAD

**Issue by tsm80** [Rhym/silverstripe-cms-theme#8]
Hi,

I noticed the module has some problems with Silverstripe 3.2. Do you know when the module will be made compatible with Silverstripe 3.2?

For example: in CMS when choosing a page in the Site Tree, the left menu collapses to the left and cannot be brought back into display.

Thanks!

**Comment by Rhym** [comment]
I'm currently overseas, so upgrade will most likely happen within the next
two weeks.

**Comment by tsm80** [comment]
OK, thanks, I'll wait for the next release then.

**Comment by stevie-mayhew** [comment]
Closed with #9
